#!/bin/sh

# print the agent section heading
echo '<<<sesam:sep(9)>>>'

# define sesam ini file
sesam_ini_file=/etc/sesam2000.ini

# initialize
read_ini()
{
  source $(grep -i '^sm_ini=' $sesam_ini_file | cut -d"=" -f2) 2>/dev/null
}
read_ini
source ${gv_rw_ini}/sesam2000.profile > /dev/null 2>&1

# get the latest status file available
latest_status_file=$(ls -tr $gv_rw_prot/*.status | tail -n2 | head -n1) 

# parse that file so it can be processed by the check
egrep -v '^Start|-------' | $latest_status_file | awk '{printf $1 "\t" $2 "\t" $3 "\t" $4 "\t" $5 "\t" $6 "\t"; for(i=7;i<NF;i++){ printf " %s", $i} printf "\n" }'
